spring.application.name=final_projest_java

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/gamehub
spring.data.mongodb.database=gamehub

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Server
server.port=8080